# Generated by Django 4.0.1 on 2022-01-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('suite', models.CharField(max_length=255, verbose_name='квартира')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('zipcode', models.CharField(max_length=10, verbose_name='почтовый индекс')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lng', models.FloatField(verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('catchphrase', models.CharField(max_length=255)),
                ('bs', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='внешний идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='логин')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=32, verbose_name='номер телефона')),
                ('website', models.URLField(verbose_name='веб-сайт')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='forum.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='forum.company')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='внешний идентификатор')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
